#!/usr/bin/env bash
# Configure nginx to listen to port 80

# stop nginx processes that are running
pkill nginx

# Change the config file to listen to port 80
sed -i 's/listen 8080/listen 80/' /etc/nginx/sites-enabled/default

# start nginx
service nginx restart
