#!/usr/bin/env bash
# A script that displays a list of current running processes.
# Show all processes, for all users, including those which might not have a TTY
#  Display in user-oriented format
#  Show Process hierarchy

ps -auxf
