#!/usr/bin/env bash
# A script that creates the file /var/run/myscript.pid containing its PID
# Displays To infinity and beyond
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y u no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/myscript.pid upon receiving the SIGQUIT or SIGTERM
#     signals.

terminate(){
	rm /var/run/myscript.pid
	exit
}

echo "$$" > /var/run/myscript.pid

while true
do
	sleep 2
	echo "To infinty and beyond"
	trap 'echo "I hate the kill command" && terminate' SIGTERM
	trap 'echo "Y u no love me?!"' SIGINT
	trap terminate SIGQUIT
done
