#!/usr/bin/env bash
# A Bash(init)script that manages `manage_the_process`
#  When passing the argument `start`:
#  1. Starts `manage_my_process`
#  2. Creates a file containing its own PID in /var/run/my_process.pid
#  3. Displays manage_my_process started
#
#  When passing the argument `stop`:
#  1. Stops manage_my_process
#  2. Deletes the file /var/run/my_process.pid
#  3. Displays manage_my_process stopped
#
#  When passing the argument `restart`:
#  1. Stops manage_my_process
#  2. Deletes the file /var/run/my_process.pid
#  3. Starts manage_my_process
#  4. Creates a file containing its PID in /var/run/my_process.pid
#  5. Displays manage_my_process restarted
#
#  if no argument is passed
#  Displays Usage: manage_my_process {start|stop|restart}

if [ "${1}" == "start" ]; then
	./manage_my_process &
	echo "$$" > /var/run/my_process.pid
	echo "manage_my_process started"

elif [ "${1}" == "stop" ]; then
	kill "$(cat /var/run/my_process.pid)"
	rm /var/run/my_process.pid
	echo "manage_my_process stopped"

elif [ "${1}" == "restart" ]; then
	kill "$(cat /var/run/my_process.pid)"
	rm /var/run/my_process.pid
	./manage_my_process &
	echo "$$" > /var/run/my_process.pid
	echo "manage_my_process restarted"
else
	echo "Usage: manage_my_process {start|stop|restart}"
fi	
