#!/usr/bin/env bash
# A script that configures an Ubuntu Server
#  - Localhost resolves to 127.0.0.2
#  - facebook.com resolves to 8.8.8.8
cp /etc/hosts ~/hosts.new
echo "127.0.0.2		Localhost" > ~/hosts.new
echo "8.8.8.8		facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
